apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jjh-order-backend
  namespace: junan-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jjh-order-backend
  template:
    metadata:
      labels:
        app: jjh-order-backend
    spec:
      containers:
      - name: jjh-order-backend
        image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/jjh-order-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: jjh-app-secrets
              key: DB_HOST
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: jjh-app-secrets
              key: DB_PW
        # - name: REDIS_HOST
        #   valueFrom:
        #     secretKeyRef:
        #       name: jjh-app-secrets
        #       key: REDIS_HOST
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: jjh-app-secrets
              key: AWS_KEY
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: jjh-app-secrets
              key: AWS_SECRET
           # 컨테이너 상태 확인 
        readinessProbe:
          httpGet:
            # healthcheck 경로
            path: /product/list
            port: 8080
          # 컨테이너 시작 후 지연
          initialDelaySeconds: 10
          # 확인 반복 주기
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: jjh-order-backend-service
  namespace: junan-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: jjh-order-backend